version: '3.3'
services:
  ball_redis_db:
    image: "redis:latest"
    container_name: ball_redis_db
    hostname: ball_redis_db
    volumes:
      - ball_redis_db_volume:/data
    networks:
      - ball_shared_network
    restart: always
  ball_postgres_db:
    image: "postgres:latest"
    container_name: ball_postgres_db
    hostname: ball_postgres_db
    environment:
      POSTGRES_PASSWORD: erfi.008
      POSTGRES_USER: postgres
      TZ: "Asia/Tehran"
    volumes:
      - ball_postgres_db_volume:/var/lib/postgresql/data
      - ./conf.d/dev-postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - ball_shared_network
    restart: always
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  ball_minio_file_storage:
    image: "minio/minio:latest"
    container_name: ball_minio_file_storage
    hostname: ball_minio_file_storage
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFOERFIEXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnERFI7MDENGbPxRfiCYEXAMPLEKEY
    command: minio server /data 
    volumes:
      - ball_minio_file_storage_volume:/data
    networks:
      - ball_shared_network
    restart: always
  dev_ball_server:
    build:
      context: .
      dockerfile: dev-dockerfile-web
    image: dev_ball_server
    container_name: dev_ball_server
    hostname: dev_ball_server
    environment:
      WAIT_HOSTS: ball_postgres_db:5432, ball_redis_db:6379, ball_minio_file_storage:9000
      ENV: production
      TZ: "Asia/Tehran"
    depends_on:
      - ball_postgres_db
      - ball_redis_db
      - ball_minio_file_storage
    command: bash -c "/wait && npm start"
    networks:
      - ball_shared_network
    restart: always
  dev_ball_nginx_proxy:
    build:
      context: .
      dockerfile: dev-dockerfile-webserver
    image: dev_ball_nginx_proxy
    container_name: dev_ball_nginx_proxy
    hostname: dev_ball_nginx_proxy
    networks:
      - ball_shared_network
      - arax_office_server_network
    volumes:
      - ./public:/var/www/static-files/
    depends_on:
      - dev_ball_server
    ports:
      - "8000:80"
volumes:
  ball_postgres_db_volume:
  ball_redis_db_volume:
  ball_minio_file_storage_volume:
networks:
  ball_shared_network:
  arax_office_server_network:
    external: true